a4p1Server: a4p1Server.c
	gcc a4p1Server.c -o a4p1Server -lnsl -lpthread
a4p2Server: a4p2Server.c
	gcc a4p2Server.c -o a4p2Server -lnsl -lpthread
a4p1client: a4p1client.c 
	gcc a4p1client.c -o a4p1client
a4p2client1: a4p2client1.c 
	gcc a4p2client1.c -o a4p2client1
a4p2client2: a4p2client2.c 
	gcc a4p2client2.c -o a4p2client2

